//MESSAGE
export const SEND_MESSAGE_START = "SEND_MESSAGE_START";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";
export const FETCH_MESSAGES_START = "FETCH_MESSAGE_START";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGE_SUCCESS";
export const FETCH_MESSAGES_FAIL = "FETCH_MESSAGE_FAIL";
export const UPDATE_MESSAGES_START = "UPDATE_MESSAGE_START";
export const UPDATE_MESSAGES_SUCCESS = "UPDATE_MESSAGE_SUCCESS";
export const UPDATE_MESSAGES_FAIL = "UPDATE_MESSAGE_FAIL";
//RESERVATIONS
export const FETCH_RESERVATIONS_START = "FETCH_RESERVATION_START";
export const FETCH_RESERVATIONS_SUCCESS = "FETCH_RESERVATION_SUCCESS";
export const FETCH_RESERVATIONS_FAIL = "FETCH_RESERVATION_FAIL";
export const UPDATE_RESERVATION_START = "UPDATE_RESERVATIONS_START";
export const UPDATE_RESERVATION_SUCCESS = "UPDATE_RESERVATIONS_SUCCESS";
export const UPDATE_RESERVATION_FAIL = "UPDATE_RESERVATIONS_FAIL";
//ALL DATA
export const FETCH_DATA_START = "FETCH_DATA_START";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAIL = "FETCH_DATA_FAIL";
//HISTORY
export const FETCH_HISTORY_START = "FETCH_HISTORY_START";
export const FETCH_HISTORY_SUCCESS = "FETCH_HISTORY_SUCCESS";
export const FETCH_HISTORY_FAIL = "FETCH_HISTORY_FAIL";
//ORDERS
export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";
export const UPDATE_ORDERS_START = "UPDATE_ORDERS_START";
export const UPDATE_ORDERS_SUCCESS = "UPDATE_ORDERS_SUCCESS";
export const UPDATE_ORDERS_FAIL = "UPDATE_ORDERS_FAIL";
//LOGIN
export const LOG_IN_START = "LOG_IN_START";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAIL = "LOG_IN_FAIL";
//LOGOUT
export const LOG_OUT_START = "LOG_OUT_START";
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export const LOG_OUT_FAIL = "LOG_OUT_FAIL";
//DELETE
export const MOVE_TO_HISTORY = "MOVE_TO_HISTORY ";
export const SCREEN_RESIZE = "SCREEN_RESIZE ";
